spring:
  cloud:
    gateway:
      routes:
        - id: microservice-patientui
          uri: http://localhost:9001
          predicates:
            - Path=/**
        - id: microservice-mongodb
          uri: http://localhost:9004
          predicates:
            - Path=/**
        - id: microservice-back
          uri: localhost:9002
          predicates:
            - Path=/**