spring:
  cloud:
    gateway:
      routes:
        - id: microservice-patientui
          uri: http://host.docker.internal:9001
          predicates:
            - Path=/**
        - id: microservice-mongodb
          uri: http://host.docker.internal:9004
          predicates:
            - Path=/**
        - id: microservice-back
          uri: http://host.docker.internal:9002
          predicates:
            - Path=/**
        - id: microservice-riskevaluator
          uri: http://host.docker.internal:9005
          predicates:
            - Path=/**